[workspace]
members = [
    "web",
    "cli",
]

[workspace.dependencies]
envir = "0.4"
elephantry = "4.0"
log = "0.4"
thiserror = "2.0"

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]
