[workspace]
members = [
    "web",
    "cli",
]

[workspace.dependencies]
envir = "0.2"
elephantry = "4.0"
env_logger = "0.11"
log = "0.4"
thiserror = "1.0"

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]
