[workspace]
members = [
    "web",
    "cli",
]

[workspace.dependencies]
dotenv = "0.15"
elephantry = "3.0"
env_logger = "0.10"
log = "0.4"
thiserror = "1.0"

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]
