[workspace]
resolver = "3"
members = [
    "web",
    "cli",
]

[workspace.package]
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
envir = "1.0"
elephantry = "5.1"
log = "0.4"
thiserror = "2.0"

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]
