[package]
name = "captainstat-web"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-files = "0.5"
actix-web = "3.3"
dotenv = "0.15"
env_logger = "0.8"
log = "0.4"
tera = "1.5"
tera-hot = "0.3"
thiserror = "1.0"

[dependencies.elephantry]
version = "2.1"
features = ["serde"]

[dependencies.elephantry-extras]
version = "0.2"
features = ["tera-pager"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
