[package]
name = "captainstat-web"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-files = "0.4"
actix-web = "3.3"
dotenv = "0.15"
elephantry = "1.3"
log = "0.4"
pretty_env_logger = "0.4"
tera = "1.5"
tera-hot = "0.2"
thiserror = "1.0"
